export 
  const ActionTypes = {
  SET_COINS: "SET_COINS",
  SELECTED_COIN: "SELECTED_COIN",
  REMOVE_SELECTED_COIN: "REMOVE_SELECTED_COIN",
  SELECTED_COIN_PRICE: "SELECTED_COIN_PRICE",
  REMOVE_SELECTED_COIN_PRICE: "REMOVE_SELECTED_COIN_PRICE",
};

